import React, { createContext, useContext, useState, useEffect } from 'react';

export type Language = 'en' | 'he';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  isRTL: boolean;
}

const translations = {
  en: {
    // Header
    'nav.solutions': 'Solutions',
    'nav.industries': 'Industries',
    'nav.resources': 'Resources',
    'nav.about': 'About',
    'nav.marketplace': 'Marketplace',
    'nav.contact': 'Contact',
    'nav.book_strategy_call': 'Book Strategy Call',
    
    // Hero Section
    'hero.we_build_apps': 'We Build Apps',
    'hero.that_make_you_rich': 'That Make You Rich',
    'hero.subtitle': 'From idea to $1M+ revenue in 12 months. We\'ve helped 247+ founders build apps that scale, raise funding, and dominate their markets.',
    'hero.trusted_by_founders': 'Trusted by founders who\'ve raised $50M+ total',
    'hero.book_strategy_call': 'Get Your App Built → FREE Strategy Call',
    'hero.next_batch_spots': '⚡ Next Batch: 3 Spots Left for Q1 2025',
    'hero.revenue_guarantee': '💰 Revenue in 90 Days or We Work Free',
    'hero.social_proof': '500+ Apps Built • $100M+ Revenue Generated • 50+ Successful Exits',
    
    // Services Section
    'services.title': 'Apps We Build That Make Bank',
    'services.subtitle': 'We don\'t just code. We build profit-generating machines that scale to millions.',
    'services.saas.title': 'SaaS Apps',
    'services.saas.subtitle': 'That Scale to $1M+ ARR',
    'services.saas.description': '🚀 We\'ve built 47+ SaaS apps that hit $100K+ MRR within 8 months.',
    'services.saas.feature1': 'Multi-tenant architecture that scales to 1M+ users',
    'services.saas.feature2': 'Built-in payment processing & subscription management',
    'services.saas.feature3': 'Advanced analytics dashboard for growth tracking',
    'services.mobile.title': 'Mobile Apps',
    'services.mobile.subtitle': 'With 500K+ Downloads',
    'services.mobile.description': '📱 Native iOS & Android apps that users obsess over.',
    'services.mobile.feature1': 'App Store optimization for viral growth',
    'services.mobile.feature2': 'Push notification system that converts',
    'services.mobile.feature3': 'In-app purchases & monetization built-in',
    'services.mobile.feature4': 'Social sharing features for organic growth',
    'services.mobile.feature5': 'Advanced user analytics & behavior tracking',
    'services.ecommerce.title': 'E-commerce',
    'services.ecommerce.subtitle': 'Apps Doing $10K+/Day',
    'services.ecommerce.description': '💰 Custom e-commerce platforms that convert at 8%+ rates.',
    'services.ecommerce.feature1': 'AI-powered product recommendations',
    'services.ecommerce.feature2': 'One-click checkout optimization',
    'services.ecommerce.feature3': 'Inventory management & automated reordering',
    'services.ecommerce.feature4': 'Multi-payment gateway integration',
    'services.ecommerce.feature5': 'Advanced sales analytics & reporting',
    'services.ai_powered.title': 'AI-Powered',
    'services.ai_powered.subtitle': 'Apps That Go Viral',
    'services.ai_powered.description': '🤖 Revolutionary AI apps that get featured on Product Hunt.',
    'services.ai_powered.feature1': 'Custom AI models trained on your data',
    'services.ai_powered.feature2': 'Natural language processing capabilities',
    'services.ai_powered.feature3': 'Machine learning algorithms that improve',
    'services.ai_powered.feature4': 'Automated content generation features',
    'services.fintech.title': 'FinTech',
    'services.fintech.subtitle': 'Apps That Handle Millions',
    'services.fintech.description': '💳 Secure financial apps with bank-level security.',
    'services.fintech.feature1': 'PCI DSS compliant payment processing',
    'services.fintech.feature2': 'Advanced fraud detection algorithms',
    'services.fintech.feature3': 'Real-time transaction monitoring',
    'services.fintech.feature4': 'Multi-currency support & exchange',
    'services.fintech.feature5': 'Automated compliance reporting',
    'services.marketplace.title': 'Marketplace',
    'services.marketplace.subtitle': 'Apps Like Uber & Airbnb',
    'services.marketplace.description': '🏪 Two-sided marketplaces that create ecosystems.',
    'services.marketplace.feature1': 'Dual user interfaces (buyers & sellers)',
    'services.marketplace.feature2': 'Automated matching algorithms',
    'services.marketplace.feature3': 'Escrow payment system',
    'services.marketplace.feature4': 'Rating & review management',
    'services.marketplace.feature5': 'Commission tracking & automated payouts',
    
    // Outcomes Section
    'outcomes.title': 'Measurable Outcomes',
    'outcomes.subtitle': 'Real results that impact your bottom line and competitive advantage',
    'outcomes.cost_reduction.value': '60%',
    'outcomes.cost_reduction.label': 'Cost Reduction',
    'outcomes.cost_reduction.title': 'Reduce Time & Cost',
    'outcomes.cost_reduction.description': 'Automate repetitive tasks and streamline processes to cut operational costs by up to 60%',
    'outcomes.customer_experience.value': '3x',
    'outcomes.customer_experience.label': 'Faster Response',
    'outcomes.customer_experience.title': 'Improve Customer Experience',
    'outcomes.customer_experience.description': 'Deliver faster, more accurate responses and personalized interactions at scale',
    'outcomes.decision_making.value': '95%',
    'outcomes.decision_making.label': 'Accuracy Boost',
    'outcomes.decision_making.title': 'Scale Better Decision-Making',
    'outcomes.decision_making.description': 'Enable data-driven decisions with real-time insights and predictive analytics',
    'outcomes.productivity.value': '2x',
    'outcomes.productivity.label': 'Productivity Gain',
    'outcomes.productivity.title': 'Accelerate Growth',
    'outcomes.productivity.description': 'Focus your team on high-value work while AI handles routine operations',
    
    // Industries Page
    'industries.page_title': 'Industries We Transform',
    'industries.page_subtitle': 'Specialized AI automation solutions tailored to your industry\'s unique challenges and requirements.',
    
    // Industry Categories
    'industries.fintech.title': 'Fintech',
    'industries.fintech.description': 'Automate compliance, risk assessment, and customer onboarding while maintaining security and regulatory requirements.',
    'industries.fintech.challenge1': 'Complex regulatory compliance',
    'industries.fintech.challenge2': 'Manual KYC processes',
    'industries.fintech.challenge3': 'Risk assessment delays',
    'industries.fintech.challenge4': 'Fraud detection',
    'industries.fintech.solution1': 'Automated KYC/AML workflows',
    'industries.fintech.solution2': 'Real-time risk scoring',
    'industries.fintech.solution3': 'Intelligent fraud detection',
    'industries.fintech.solution4': 'Regulatory reporting automation',
    'industries.fintech.result1': '90% faster onboarding',
    'industries.fintech.result2': '95% compliance accuracy',
    'industries.fintech.result3': '60% reduction in fraud cases',
    
    'industries.customer_experience.title': 'Customer Experience',
    'industries.customer_experience.description': 'Transform customer interactions with intelligent chatbots, automated support, and personalized experiences.',
    'industries.customer_experience.challenge1': 'High support volume',
    'industries.customer_experience.challenge2': 'Inconsistent responses',
    'industries.customer_experience.challenge3': 'Long resolution times',
    'industries.customer_experience.challenge4': 'Limited personalization',
    'industries.customer_experience.solution1': 'AI-powered chatbots',
    'industries.customer_experience.solution2': 'Intelligent ticket routing',
    'industries.customer_experience.solution3': 'Sentiment analysis',
    'industries.customer_experience.solution4': 'Automated response generation',
    'industries.customer_experience.result1': '70% faster response times',
    'industries.customer_experience.result2': '85% customer satisfaction',
    'industries.customer_experience.result3': '50% reduction in support costs',
    
    'industries.back_office.title': 'Back-Office / ERP',
    'industries.back_office.description': 'Streamline financial processes, inventory management, and data entry with intelligent automation.',
    'industries.back_office.challenge1': 'Manual data entry',
    'industries.back_office.challenge2': 'Invoice processing delays',
    'industries.back_office.challenge3': 'Inventory discrepancies',
    'industries.back_office.challenge4': 'Report generation',
    'industries.back_office.solution1': 'Automated invoice processing',
    'industries.back_office.solution2': 'Smart data extraction',
    'industries.back_office.solution3': 'Real-time inventory tracking',
    'industries.back_office.solution4': 'Automated reporting',
    'industries.back_office.result1': '80% faster processing',
    'industries.back_office.result2': '99% data accuracy',
    'industries.back_office.result3': '65% cost reduction',
    
    'industries.horizontal.title': 'Horizontal Processes',
    'industries.horizontal.description': 'Cross-functional automation for HR, finance, supply chain, and other enterprise-wide processes.',
    'industries.horizontal.challenge1': 'Siloed systems',
    'industries.horizontal.challenge2': 'Manual approvals',
    'industries.horizontal.challenge3': 'Data inconsistency',
    'industries.horizontal.challenge4': 'Process inefficiencies',
    'industries.horizontal.solution1': 'Workflow orchestration',
    'industries.horizontal.solution2': 'Automated approvals',
    'industries.horizontal.solution3': 'System integration',
    'industries.horizontal.solution4': 'Process optimization',
    'industries.horizontal.result1': '75% faster approvals',
    'industries.horizontal.result2': '90% process efficiency',
    'industries.horizontal.result3': 'Unified data visibility',
    
    'industries.medical.title': 'Medical',
    'industries.medical.description': 'Streamline patient care, medical records management, and compliance while maintaining HIPAA security standards.',
    'industries.medical.challenge1': 'Complex patient scheduling',
    'industries.medical.challenge2': 'Manual medical records processing',
    'industries.medical.challenge3': 'Insurance claim delays',
    'industries.medical.challenge4': 'Regulatory compliance tracking',
    'industries.medical.solution1': 'Automated patient scheduling',
    'industries.medical.solution2': 'Smart medical records processing',
    'industries.medical.solution3': 'Automated insurance claims',
    'industries.medical.solution4': 'HIPAA compliance monitoring',
    'industries.medical.result1': '60% faster patient processing',
    'industries.medical.result2': '90% claims accuracy',
    'industries.medical.result3': '40% reduction in administrative costs',
    
    'industries.accounting.title': 'Accounting',
    'industries.accounting.description': 'Automate bookkeeping, tax preparation, and financial reporting while ensuring accuracy and compliance.',
    'industries.accounting.challenge1': 'Manual data entry',
    'industries.accounting.challenge2': 'Reconciliation errors',
    'industries.accounting.challenge3': 'Time-consuming tax prep',
    'industries.accounting.challenge4': 'Client communication overhead',
    'industries.accounting.solution1': 'Automated bookkeeping',
    'industries.accounting.solution2': 'Smart reconciliation',
    'industries.accounting.solution3': 'AI-powered tax preparation',
    'industries.accounting.solution4': 'Client portal automation',
    'industries.accounting.result1': '70% faster month-end close',
    'industries.accounting.result2': '95% data accuracy',
    'industries.accounting.result3': '50% more client capacity',
    
    'industries.legal.title': 'Legal',
    'industries.legal.description': 'Enhance legal research, document review, and case management with intelligent automation and analysis.',
    'industries.legal.challenge1': 'Time-intensive document review',
    'industries.legal.challenge2': 'Manual legal research',
    'industries.legal.challenge3': 'Contract analysis bottlenecks',
    'industries.legal.challenge4': 'Client billing complexity',
    'industries.legal.solution1': 'AI document review',
    'industries.legal.solution2': 'Automated legal research',
    'industries.legal.solution3': 'Smart contract analysis',
    'industries.legal.solution4': 'Automated time tracking and billing',
    'industries.legal.result1': '80% faster document review',
    'industries.legal.result2': '60% more efficient research',
    'industries.legal.result3': '45% increase in billable hours',
    
    // Industries Common Labels
    'industries.common_challenges': 'Common Challenges',
    'industries.our_solutions': 'Our Solutions',
    'industries.typical_results': 'Typical Results',
    'industries.ready_to_transform': 'Ready to Transform Your Industry?',
    'industries.consultation_description': 'Let\'s discuss how AI automation can address your specific industry challenges.',
    'industries.get_consultation': 'Get Industry-Specific Consultation',
    'industries.title': 'Industries We Transform',
    'industries.subtitle': 'Specialized solutions tailored to your industry\'s unique challenges and requirements',
    'industries.key_use_cases': 'Key Use Cases',
    
    // Process Section
    'process.title': 'Our Process',
    'process.subtitle': 'A proven methodology that ensures successful AI implementation',
    'process.discover.title': 'Discover',
    'process.discover.description': 'We analyze your current processes to identify automation opportunities and quick wins.',
    'process.discover.detail1': 'Process Assessment',
    'process.discover.detail2': 'Opportunity Mapping',
    'process.discover.detail3': 'ROI Analysis',
    'process.pilot.title': 'Pilot',
    'process.pilot.description': 'Rapid prototyping and testing of AI solutions with measurable success metrics.',
    'process.pilot.detail1': 'Proof of Concept',
    'process.pilot.detail2': 'Performance Testing',
    'process.pilot.detail3': 'Success Metrics',
    'process.scale.title': 'Scale',
    'process.scale.description': 'Full implementation with enterprise-grade infrastructure and change management.',
    'process.scale.detail1': 'Full Deployment',
    'process.scale.detail2': 'Team Training',
    'process.scale.detail3': 'Change Management',
    'process.operate.title': 'Operate',
    'process.operate.description': 'Ongoing optimization, monitoring, and support to ensure continued success.',
    'process.operate.detail1': 'Performance Monitoring',
    'process.operate.detail2': 'Continuous Optimization',
    'process.operate.detail3': 'Support & Maintenance',
    
     // Trust Section
    'trust.title': 'Join 247+ Successful Founders',
    'trust.subtitle': 'Real founders. Real apps. Real results. See why top entrepreneurs choose us to build their next big thing.',
    'trust.stats.clients': 'Enterprise Clients',
    'trust.stats.automations': 'Automations Deployed',
    'trust.stats.uptime': 'Uptime Guarantee',
    'trust.stats.costReduction': 'Average Cost Reduction',
    'trust.testimonials.testimonial1.quote': 'The AI automation solutions transformed our customer service operations, reducing response time by 70% while improving satisfaction scores.',
    'trust.testimonials.testimonial1.author': 'Sarah Johnson',
    'trust.testimonials.testimonial1.role': 'VP of Operations',
    'trust.testimonials.testimonial1.company': 'TechCorp',
    'trust.testimonials.testimonial2.quote': 'Implementation was seamless and the ROI was evident within the first quarter. Our team can now focus on strategic initiatives.',
    'trust.testimonials.testimonial2.author': 'Michael Chen',
    'trust.testimonials.testimonial2.role': 'CTO',
    'trust.testimonials.testimonial2.company': 'FinanceFlow',
    'trust.testimonials.testimonial3.quote': 'The level of customization and enterprise-grade security exceeded our expectations. Highly recommend for any serious automation project.',
    'trust.testimonials.testimonial3.author': 'Emily Rodriguez',
    'trust.testimonials.testimonial3.role': 'Chief Digital Officer',
    'trust.testimonials.testimonial3.company': 'ManufacturePlus',
    'trust.trustedBy': 'Trusted by leading companies worldwide',
    
    // CTA Section
    'cta.title': 'Ready to Transform Your Business?',
    'cta.subtitle': 'Start your AI automation journey today with a free consultation',
    'cta.button': 'Get Started Now',
    
    // Contact Page
    'contact.title': 'Tell Us About Your Project',
    'contact.subtitle': 'Fill out the form below and we\'ll get back to you within 24 hours with a custom proposal.',
    'contact.success': 'Message sent successfully!',
    'contact.error': 'Failed to send message. Please try again.',
    'contact.get_in_touch': 'Get In Touch',
    'contact.phone': 'Phone',
    'contact.email': 'Email',
    'contact.phone_description': 'Speak with our team directly',
    'contact.email_description': 'Send us a detailed message',
    'contact.phone_availability': 'Mon-Fri, 9am-6pm EST',
    'contact.email_availability': 'Response within 24 hours',
    'contact.quick_actions': 'Quick Actions',
    'contact.schedule_call': 'Schedule a Call',
    'contact.book_assessment': 'Book Free Assessment',
    'contact.promise': 'Our Promise',
    'contact.promise_description': 'We respond to all inquiries within 24 hours and provide custom proposals within 48 hours.',
    'contact.form.name': 'Full Name',
    'contact.form.email': 'Email Address',
    'contact.form.company': 'Company Name',
    'contact.form.industry': 'Industry',
    'contact.form.industry.placeholder': 'Select your industry',
    'contact.form.industry.healthcare': 'Healthcare',
    'contact.form.industry.finance': 'Finance',
    'contact.form.industry.retail': 'Retail',
    'contact.form.industry.manufacturing': 'Manufacturing',
    'contact.form.industry.technology': 'Technology',
    'contact.form.industry.education': 'Education',
    'contact.form.industry.other': 'Other',
    'contact.form.project_type': 'Project Type',
    'contact.form.project_type.placeholder': 'Select project type',
    'contact.form.project_type.ai_automation': 'AI Automation',
    'contact.form.project_type.process_optimization': 'Process Optimization',
    'contact.form.project_type.data_analysis': 'Data Analysis',
    'contact.form.project_type.custom_integration': 'Custom Integration',
    'contact.form.timeline': 'Timeline',
    'contact.form.timeline.placeholder': 'Select timeline',
    'contact.form.timeline.urgent': 'ASAP (Rush)',
    'contact.form.timeline.1_3_months': '1-3 months',
    'contact.form.timeline.3_6_months': '3-6 months',
    'contact.form.timeline.6_plus_months': '6+ months',
    'contact.form.budget': 'Budget Range',
    'contact.form.budget.placeholder': 'Select budget range',
    'contact.form.budget.discuss': 'Let\'s discuss',
    'contact.form.budget.10k_25k': '$10k - $25k',
    'contact.form.budget.25k_50k': '$25k - $50k',
    'contact.form.budget.50k_100k': '$50k - $100k',
    'contact.form.budget.100k_plus': '$100k+',
    'contact.form.message': 'Project Details',
    'contact.form.message.placeholder': 'Tell us about your project, current challenges, and what you hope to achieve with AI automation...',
    'contact.form.submit': 'Send Message',
    'contact.form.submitting': 'Sending...',

    // About Page
    'about.hero.title1': 'Building the Future',
    'about.hero.title2': 'of Business Automation',
    'about.hero.description': 'We\'re on a mission to democratize AI automation, making enterprise-grade solutions accessible to businesses of all sizes.',
    'about.mission.title': 'Our Mission',
    'about.mission.description1': 'We believe that AI automation should be secure, scalable, and accessible. Our mission is to help businesses harness the power of artificial intelligence to eliminate repetitive work, reduce errors, and unlock human potential.',
    'about.mission.description2': 'By combining deep technical expertise with real-world business experience, we deliver solutions that don\'t just work—they transform how businesses operate and compete.',
    'about.mission.learn_more': 'Learn More About Our Approach',
    'about.stats.clients': 'Enterprise Clients',
    'about.stats.automations': 'Automations Deployed',
    'about.stats.experience': 'Years Experience',
    'about.stats.uptime': 'Uptime',
    'about.values.title': 'Our Values',
    'about.values.description': 'The principles that guide everything we do and every solution we build.',
    'about.values.trust.title': 'Trust',
    'about.values.trust.description': 'We build secure, reliable AI systems that enterprises can depend on with enterprise-grade security and compliance.',
    'about.values.innovation.title': 'Innovation',
    'about.values.innovation.description': 'We stay at the forefront of AI technology to deliver cutting-edge solutions that drive real business value.',
    'about.values.impact.title': 'Impact',
    'about.values.impact.description': 'We focus on measurable outcomes that transform businesses and create lasting competitive advantages.',
    'about.values.partnership.title': 'Partnership',
    'about.values.partnership.description': 'We work closely with our clients as true partners, ensuring successful adoption and long-term success.',
    'about.team.title': 'Meet Our Team',
    'about.team.description': 'Experienced professionals passionate about transforming businesses through AI automation.',
    'about.team.or.name': 'Or Sela',
    'about.team.or.role': 'CEO & Founder',
    'about.team.or.speciality': 'AI Strategy & Business Development',
    'about.team.or.description': 'Visionary leader driving AI automation transformation across enterprises.',
    'about.team.idan.name': 'Idan Ayalon',
    'about.team.idan.role': 'CTO & Founder',
    'about.team.idan.speciality': 'Technical Architecture & Innovation',
    'about.team.idan.description': 'Expert in building scalable AI systems and automation platforms.',
    'about.cta.title': 'Ready to Work Together?',
    'about.cta.description': 'Let\'s discuss how we can help transform your business with AI automation.',
    'about.cta.button': 'Start the Conversation',
    
    // Marketplace
    'marketplace.title': 'Automation Marketplace',
    'marketplace.subtitle': 'Discover and implement pre-built automation workflows',
    'marketplace.search.placeholder': 'Search automations...',
    'marketplace.all_categories': 'All Categories',
    'marketplace.automations_found': 'automations found',
    'marketplace.no_automations': 'No automations found matching your criteria.',
    'marketplace.back_to_marketplace': 'Back to Marketplace',
    'marketplace.use_automation': 'Use This Automation',
    'marketplace.watch_tutorial': 'Watch Tutorial',
    'marketplace.about_automation': 'About This Automation',
    'marketplace.quality_score': 'Quality Score',
    'marketplace.category': 'Category',
    'marketplace.platform': 'Platform',
    
    // Not Found
    'notfound.title': '404',
    'notfound.subtitle': 'Oops! Page not found',
    'notfound.back_home': 'Return to Home',
    
    // Resources Page
    'resources.title': 'Hub',
    'resources.subtitle': 'Explore our comprehensive library of guides, case studies, and insights to accelerate your AI automation journey.',
    'resources.guides.title': 'Guides & Whitepapers',
    'resources.guides.whitepaper.type': 'Whitepaper',
    'resources.guides.whitepaper.duration': '15 min read',
    'resources.guides.whitepaper.title': 'Enterprise AI Implementation Guide',
    'resources.guides.whitepaper.description': 'A comprehensive guide to implementing AI solutions in enterprise environments.',
    'resources.guides.guide.type': 'Guide',
    'resources.guides.guide.duration': '10 min read',
    'resources.guides.guide.title': 'RPA Best Practices for Finance Teams',
    'resources.guides.guide.description': 'Learn how to successfully implement RPA in financial processes.',
    'resources.guides.framework.type': 'Framework',
    'resources.guides.framework.duration': '20 min read',
    'resources.guides.framework.title': 'AI Safety & Governance Framework',
    'resources.guides.framework.description': 'Essential framework for ensuring AI safety and compliance in your organization.',
    'resources.cases.title': 'Case Studies',
    'resources.cases.fintech.type': 'Case Study',
    'resources.cases.fintech.duration': '8 min read',
    'resources.cases.fintech.title': 'Fintech Company Reduces Processing Time by 80%',
    'resources.cases.fintech.description': 'How a leading fintech automated their customer onboarding process.',
    'resources.cases.manufacturing.type': 'Case Study',
    'resources.cases.manufacturing.duration': '12 min read',
    'resources.cases.manufacturing.title': 'Manufacturing Giant Optimizes Supply Chain',
    'resources.cases.manufacturing.description': 'AI-powered supply chain optimization delivers 60% efficiency gains.',
    'resources.webinars.title': 'Webinars & Videos',
    'resources.webinars.future.type': 'Webinar',
    'resources.webinars.future.duration': '45 min watch',
    'resources.webinars.future.title': 'Future of AI Automation in 2024',
    'resources.webinars.future.description': 'Join our experts as they discuss emerging trends in AI automation.',
    'resources.webinars.generative.type': 'Video Series',
    'resources.webinars.generative.duration': '30 min watch',
    'resources.webinars.generative.title': 'Getting Started with Generative AI',
    'resources.webinars.generative.description': 'A practical introduction to implementing generative AI in your business.',
    'resources.insights.title': 'Latest Insights',
    'resources.insights.subtitle': 'Stay updated with the latest trends and insights in AI automation.',
    'resources.insights.trends.category': 'Trends',
    'resources.insights.trends.date': 'March 15, 2024',
    'resources.insights.trends.title': 'Hyperautomation Trends: What to Expect in 2024',
    'resources.insights.trends.description': 'Explore the latest trends in hyperautomation and how they\'ll shape business processes.',
    'resources.insights.trends.duration': '5 min read',
    'resources.insights.ethics.category': 'AI Ethics',
    'resources.insights.ethics.date': 'March 10, 2024',
    'resources.insights.ethics.title': 'Building Ethical AI Systems for Enterprise',
    'resources.insights.ethics.description': 'Best practices for developing AI systems that are ethical, transparent, and compliant.',
    'resources.insights.ethics.duration': '8 min read',
    'resources.insights.business.category': 'Business Value',
    'resources.insights.business.date': 'March 5, 2024',
    'resources.insights.business.title': 'ROI Calculator: Measuring AI Automation Success',
    'resources.insights.business.description': 'Learn how to calculate and track the ROI of your AI automation initiatives.',
    'resources.insights.business.duration': '6 min read',
    'resources.newsletter.title': 'Stay Informed',
    'resources.newsletter.description': 'Get the latest insights and resources delivered to your inbox monthly.',
    'resources.newsletter.button': 'Subscribe to Newsletter',
    'resources.download': 'Download',
    'resources.read_more': 'Read More',
    'resources.view_all_posts': 'View All Posts',

    // Solutions Page
    'solutions.hero.title': 'Solutions Built',
    'solutions.hero.subtitle': 'for Real Impact',
    'solutions.hero.description': 'Comprehensive AI and automation solutions designed to transform your business operations and drive measurable results.',
    'solutions.ai_automation.title': 'AI Automation',
    'solutions.ai_automation.description': 'Intelligent workflows that adapt and optimize themselves, reducing manual intervention while increasing accuracy and speed.',
    'solutions.ai_automation.feature1': 'Smart Process Mining',
    'solutions.ai_automation.feature2': 'Adaptive Workflows',
    'solutions.ai_automation.feature3': 'Predictive Analytics',
    'solutions.ai_automation.feature4': 'Real-time Optimization',
    'solutions.ai_automation.benefit1': '60% reduction in processing time',
    'solutions.ai_automation.benefit2': '95% accuracy improvement',
    'solutions.ai_automation.benefit3': '24/7 automated operations',
    'solutions.generative_ai.title': 'Generative AI Solutions',
    'solutions.generative_ai.description': 'Custom AI models for content creation, data analysis, and decision support tailored to your business needs.',
    'solutions.generative_ai.feature1': 'Custom LLM Integration',
    'solutions.generative_ai.feature2': 'Content Generation',
    'solutions.generative_ai.feature3': 'Data Insights',
    'solutions.generative_ai.feature4': 'Natural Language Processing',
    'solutions.generative_ai.benefit1': '3x faster content creation',
    'solutions.generative_ai.benefit2': 'Personalized customer interactions',
    'solutions.generative_ai.benefit3': 'Automated report generation',
    'solutions.enterprise_ai.title': 'Enterprise AI Development',
    'solutions.enterprise_ai.description': 'End-to-end AI system development with enterprise-grade security, scalability, and governance.',
    'solutions.enterprise_ai.feature1': 'Scalable Architecture',
    'solutions.enterprise_ai.feature2': 'Security First',
    'solutions.enterprise_ai.feature3': 'Compliance Ready',
    'solutions.enterprise_ai.feature4': 'Integration Capabilities',
    'solutions.enterprise_ai.benefit1': 'Enterprise-grade security',
    'solutions.enterprise_ai.benefit2': 'Seamless system integration',
    'solutions.enterprise_ai.benefit3': 'Regulatory compliance',
    'solutions.consulting.title': 'AI Consulting & Adoption',
    'solutions.consulting.description': 'Strategic guidance to identify opportunities, plan implementation, and ensure successful AI adoption.',
    'solutions.consulting.feature1': 'Strategy Development',
    'solutions.consulting.feature2': 'Change Management',
    'solutions.consulting.feature3': 'Training Programs',
    'solutions.consulting.feature4': 'Performance Monitoring',
    'solutions.consulting.benefit1': 'Clear AI roadmap',
    'solutions.consulting.benefit2': 'Successful team adoption',
    'solutions.consulting.benefit3': 'Measurable ROI',
    'solutions.rpa.title': 'Robotic Process Automation',
    'solutions.rpa.description': 'Traditional RPA enhanced with AI capabilities for complex process automation and exception handling.',
    'solutions.rpa.feature1': 'Intelligent RPA',
    'solutions.rpa.feature2': 'Exception Handling',
    'solutions.rpa.feature3': 'Process Optimization',
    'solutions.rpa.feature4': 'Legacy System Integration',
    'solutions.rpa.benefit1': '80% faster processing',
    'solutions.rpa.benefit2': 'Reduced human errors',
    'solutions.rpa.benefit3': 'Legacy system modernization',
    'solutions.key_features': 'Key Features:',
    'solutions.benefits': 'Benefits:',
    'solutions.visual.placeholder': 'Solution Visualization',
    'solutions.cta.title': 'Ready to Get',
    'solutions.cta.subtitle': 'Started?',
    'solutions.cta.description': 'Let\'s discuss which solution is right for your business needs.',
    'solutions.cta.button': 'Book a Strategy Call',

    // Assistant Chat
    'assistant.greeting': 'How can I help your business?',
    'assistant.input_placeholder': 'Ask me about AI automation...',
    'assistant.hello_response': 'Hello! I\'m here to help you discover how AI automation can transform your business. What challenges are you facing?',
    'assistant.automation_response': 'AI automation can help streamline your operations, reduce costs, and improve efficiency. Would you like to know more about our solutions for your specific industry?',
    'assistant.cost_response': 'Our solutions are tailored to your specific needs and budget. We offer flexible pricing options starting from $10k. Would you like to schedule a free consultation to discuss your requirements?',
    'assistant.contact_response': 'I\'d be happy to help you get in touch with our team! You can book a strategy call or reach out directly. What would you prefer?',
    'assistant.default_response': 'That\'s a great question! Our AI automation solutions can help with various business challenges. Could you tell me more about your specific needs so I can provide more targeted assistance?',

    // Onboarding
    'onboarding.title': 'Hey, I\'m Mate!',
    'onboarding.message': 'I\'m your assistant, let\'s talk about your business and how AI automation can help you grow.',
    'onboarding.start_chat': 'Let\'s Talk!',
    'onboarding.maybe_later': 'Maybe Later',

    // App Builder Page
    'app_builder.hero.title_a': 'From Idea to Working App in 30 Minutes',
    'app_builder.hero.subtitle_a': 'See your app come to life before you invest a penny',
    'app_builder.hero.title_b': 'See Your App Before You Build It',
    'app_builder.hero.subtitle_b': 'Get a working prototype to test with users and investors',
    'app_builder.hero.title_c': 'Know Exactly What Your App Will Cost & Look Like',
    'app_builder.hero.subtitle_c': 'Get accurate pricing, timeline, and a working prototype to test',
    'app_builder.hero.title_d': 'No Technical Knowledge Required',
    'app_builder.hero.subtitle_d': 'Our AI handles the complex stuff, you focus on your vision',
    
    'app_builder.process.docs_title': 'Get Professional Docs',
    'app_builder.process.docs_description': 'PRD, architecture & flow diagrams',
    'app_builder.process.prototype_title': 'See Working Prototype',
    'app_builder.process.prototype_description': 'Test your app in real-time',
    'app_builder.process.quote_title': 'Get Accurate Quote & POC',
    'app_builder.process.quote_description': 'Know exactly what it costs AND see how it looks',
    
    'app_builder.form.title': 'Get Your Complete App Package in 24 Hours',
    'app_builder.form.subtitle': 'Professional docs + working prototype + accurate pricing - everything you need to move forward',
    'app_builder.form.name_label': 'Full Name',
    'app_builder.form.email_label': 'Email Address',
    'app_builder.form.idea_label': 'Describe Your App Idea',
    'app_builder.form.idea_placeholder': 'Tell us what your app should do, who it\'s for, and what problems it solves...',
    'app_builder.form.industry_label': 'Industry',
    'app_builder.form.industry_placeholder': 'e.g., Healthcare, Finance, E-commerce',
    'app_builder.form.timeline_label': 'Desired Timeline',
    'app_builder.form.timeline_placeholder': 'e.g., 3 months, ASAP, Q2 2025',
    'app_builder.form.submit': 'Get My Complete Package',
    'app_builder.form.disclaimer': 'No commitment required • See cost & prototype first • 24-hour delivery',
    
    'app_builder.features.speed_title': 'Lightning Fast',
    'app_builder.features.speed_description': 'Get your working prototype in 24 hours, not weeks. Perfect for investor meetings and user testing.',
    'app_builder.features.risk_title': 'Risk-Free Validation',
    'app_builder.features.risk_description': 'See exactly what you\'re getting before investing in full development. No surprises, no regrets.',
    'app_builder.features.time_title': 'Save Months',
    'app_builder.features.time_description': 'Skip the traditional discovery phase. Our AI conversation extracts everything needed for accurate planning.',
    
    'app_builder.trust.title': 'Why Smart Founders Choose Our Validation System',
    'app_builder.social_proof.quote': 'This prototype helped us raise $2M in seed funding. Investors could actually see and test our vision.',
    'app_builder.social_proof.author': 'Sarah Chen, CEO of TechStart (Y Combinator W23)',
    
    'app_builder.chat.demo_title': 'Try Our AI App Builder',
    'app_builder.chat.demo_subtitle': 'Experience how our intelligent conversation turns your app idea into a working prototype',
    'app_builder.chat.start_button': 'Start Building My App',
    'app_builder.chat.disclaimer': 'No signup required • See results instantly • Takes 2 minutes',

    // Common
    'common.automate': '\mates',
    'common.loading': 'Loading...',
    'common.learn_more': 'Learn More',
    'common.get_started': 'Get Started',
  },
  he: {
    // Header
    'nav.solutions': 'פתרונות',
    'nav.industries': 'תעשיות',
    'nav.resources': 'משאבים',
    'nav.about': 'אודות',
    'nav.marketplace': 'חנות',
    'nav.contact': 'צור קשר',
    'nav.book_strategy_call': 'קבע פגישת אסטרטגיה',
    
    // Hero Section
    'hero.we_build_apps': 'אנחנו בונים אפליקציות',
    'hero.that_make_you_rich': 'שיהפכו אותך לעשיר',
    'hero.subtitle': 'מרעיון להכנסה של מיליון+ דולר תוך 12 חודשים. עזרנו ל-247+ מייסדים לבנות אפליקציות שמתרחבות, מגייסות מימון ומשלטות בשווקים שלהן.',
    'hero.trusted_by_founders': 'זוכים לאמון של מייסדים שגייסו יותר מ-50 מיליון דולר',
    'hero.book_strategy_call': 'בואו נבנה את האפליקציה שלך ← שיחת אסטרטגיה חינם',
    'hero.next_batch_spots': '⚡ הקבוצה הבאה: נשארו 3 מקומות לרבעון הראשון של 2025',
    'hero.revenue_guarantee': '💰 הכנסות תוך 90 יום או שנעבוד בחינם',
    'hero.social_proof': '500+ אפליקציות נבנו • 100+ מיליון דולר הכנסות • 50+ יציאות מוצלחות',
    
    // Services Section
    'services.title': 'אפליקציות שאנחנו בונים שמרוויחות',
    'services.subtitle': 'אנחנו לא סתם מתכנתים. אנחנו בונים מכונות רווח שמתרחבות למיליונים.',
    'services.saas.title': 'אפליקציות SaaS',
    'services.saas.subtitle': 'שמתרחבות ל-1+ מיליון דולר ARR',
    'services.saas.description': '🚀 בנינו 47+ אפליקציות SaaS שהגיעו ל-100K+ דולר MRR תוך 8 חודשים.',
    'services.saas.feature1': 'ארכיטקטורה רב-משתמשים שמתרחבת ל-1+ מיליון משתמשים',
    'services.saas.feature2': 'עיבוד תשלומים וניהול מנויים מובנים',
    'services.saas.feature3': 'לוח מחוונים אנליטיקה מתקדם למעקב צמיחה',
    'services.mobile.title': 'אפליקציות מובייל',
    'services.mobile.subtitle': 'עם 500K+ הורדות',
    'services.mobile.description': '📱 אפליקציות iOS ו-Android מקוריות שמשתמשים מכורים אליהן.',
    'services.mobile.feature1': 'אופטימיזציה לחנויות האפליקציות לצמיחה ויראלית',
    'services.mobile.feature2': 'מערכת התראות דחיפה שממירה',
    'services.mobile.feature3': 'רכישות בתוך האפליקציה ומונטיזציה מובנית',
    'services.mobile.feature4': 'תכונות שיתוף חברתיות לצמיחה אורגנית',
    'services.mobile.feature5': 'אנליטיקה מתקדמת של משתמשים ומעקב התנהגות',
    'services.ecommerce.title': 'מסחר אלקטרוני',
    'services.ecommerce.subtitle': 'אפליקציות שמרוויחות 10K+ דולר ליום',
    'services.ecommerce.description': '💰 פלטפורמות מסחר אלקטרוני מותאמות אישית שממירות ב-8%+ שיעורים.',
    'services.ecommerce.feature1': 'המלצות מוצרים מונעות AI',
    'services.ecommerce.feature2': 'אופטימיזציה של קופה בלחיצה אחת',
    'services.ecommerce.feature3': 'ניהול מלאי והזמנות אוטומטיות',
    'services.ecommerce.feature4': 'שילוב מרובה שערי תשלום',
    'services.ecommerce.feature5': 'אנליטיקה מתקדמת של מכירות ודיווח',
    'services.ai_powered.title': 'מונעות AI',
    'services.ai_powered.subtitle': 'אפליקציות שהופכות לויראליות',
    'services.ai_powered.description': '🤖 אפליקציות AI מהפכניות שזוכות להצגה ב-Product Hunt.',
    'services.ai_powered.feature1': 'מודלי AI מותאמים אישית מאומנים על הנתונים שלך',
    'services.ai_powered.feature2': 'יכולות עיבוד שפה טבעית',
    'services.ai_powered.feature3': 'אלגוריתמים של למידת מכונה שמשתפרים',
    'services.ai_powered.feature4': 'תכונות יצירת תוכן אוטומטיות',
    'services.fintech.title': 'פינטק',
    'services.fintech.subtitle': 'אפליקציות שמטפלות במיליונים',
    'services.fintech.description': '💳 אפליקציות פיננסיות מאובטחות עם אבטחה ברמת בנק.',
    'services.fintech.feature1': 'עיבוד תשלומים תואם PCI DSS',
    'services.fintech.feature2': 'אלגוריתמים מתקדמים לזיהוי הונאה',
    'services.fintech.feature3': 'ניטור עסקאות בזמן אמת',
    'services.fintech.feature4': 'תמיכה רב-מטבעית וחליפין',
    'services.fintech.feature5': 'דיווח תאימות אוטומטי',
    'services.marketplace.title': 'מרקטפלייס',
    'services.marketplace.subtitle': 'אפליקציות כמו Uber ו-Airbnb',
    'services.marketplace.description': '🏪 שווקים דו-צדדיים שיוצרים מערכות אקולוגיות.',
    'services.marketplace.feature1': 'ממשקי משתמש כפולים (קונים ומוכרים)',
    'services.marketplace.feature2': 'אלגוריתמים של התאמה אוטומטיים',
    'services.marketplace.feature3': 'מערכת תשלומי נאמנות',
    'services.marketplace.feature4': 'ניהול דירוגים וביקורות',
    'services.marketplace.feature5': 'מעקב עמלות ותשלומים אוטומטיים',
    
    // Outcomes Section
    'outcomes.title': 'תוצאות מדידות',
    'outcomes.subtitle': 'תוצאות אמיתיות שמשפיעות על הרווח שלך ועל היתרון התחרותי',
    'outcomes.cost_reduction.value': '60%',
    'outcomes.cost_reduction.label': 'הפחתת עלויות',
    'outcomes.cost_reduction.title': 'הפחת זמן ועלויות',
    'outcomes.cost_reduction.description': 'הפוך משימות חוזרות לאוטומטיות וייעל תהליכים כדי לחתוך עלויות תפעוליות עד 60%',
    'outcomes.customer_experience.value': '3x',
    'outcomes.customer_experience.label': 'תגובה מהירה יותר',
    'outcomes.customer_experience.title': 'שפר חוויית הלקוח',
    'outcomes.customer_experience.description': 'העניק תגובות מהירות ומדויקות יותר ואינטראקציות מותאמות אישית בקנה מידה',
    'outcomes.decision_making.value': '95%',
    'outcomes.decision_making.label': 'שיפור דיוק',
    'outcomes.decision_making.title': 'קבלת החלטות טובה יותר בקנה מידה',
    'outcomes.decision_making.description': 'אפשר החלטות מונעות נתונים עם תובנות בזמן אמת ואנליטיקה חזויה',
    'outcomes.productivity.value': '2x',
    'outcomes.productivity.label': 'עלייה בפרודוקטיביות',
    'outcomes.productivity.title': 'האץ צמיחה',
    'outcomes.productivity.description': 'התמקד בעבודה בעלת ערך גבוה בזמן ש-AI מטפל בפעולות שגרתיות',
     
    // Industries Page
    'industries.page_title': 'תעשיות שאנו משנים',
    'industries.page_subtitle': 'פתרונות אוטומציית AI מיוחדים המותאמים לאתגרים ודרישות הייחודיים של התעשייה שלך.',
    
    // Industry Categories
    'industries.fintech.title': 'פינטק',
    'industries.fintech.description': 'אוטומציה של תאימות, הערכת סיכונים ואיוש לקוחות תוך שמירה על אבטחה ודרישות רגולטוריות.',
    'industries.fintech.challenge1': 'תאימות רגולטורית מורכבת',
    'industries.fintech.challenge2': 'תהליכי KYC ידניים',
    'industries.fintech.challenge3': 'עיכובים בהערכת סיכונים',
    'industries.fintech.challenge4': 'זיהוי הונאה',
    'industries.fintech.solution1': 'זרימות עבודה אוטומטיות של KYC/AML',
    'industries.fintech.solution2': 'ניקוד סיכונים בזמן אמת',
    'industries.fintech.solution3': 'זיהוי הונאה חכם',
    'industries.fintech.solution4': 'אוטומציה של דיווח רגולטורי',
    'industries.fintech.result1': '90% האצה באיוש',
    'industries.fintech.result2': '95% דיוק בתאימות',
    'industries.fintech.result3': '60% הפחתה במקרי הונאה',
    
    'industries.customer_experience.title': 'חוויית לקוח',
    'industries.customer_experience.description': 'שנה אינטראקציות לקוחות עם צ\'אטבוטים חכמים, תמיכה אוטומטית וחוויות מותאמות אישית.',
    'industries.customer_experience.challenge1': 'נפח תמיכה גבוה',
    'industries.customer_experience.challenge2': 'תגובות לא עקביות',
    'industries.customer_experience.challenge3': 'זמני פתרון ארוכים',
    'industries.customer_experience.challenge4': 'התאמה אישית מוגבלת',
    'industries.customer_experience.solution1': 'צ\'אטבוטים מבוססי AI',
    'industries.customer_experience.solution2': 'ניתוב כרטיסים חכם',
    'industries.customer_experience.solution3': 'ניתוח סנטימנט',
    'industries.customer_experience.solution4': 'יצירת תגובות אוטומטית',
    'industries.customer_experience.result1': '70% האצה בזמן תגובה',
    'industries.customer_experience.result2': '85% שביעות רצון לקוחות',
    'industries.customer_experience.result3': '50% הפחתה בעלויות תמיכה',
    
    'industries.back_office.title': 'משרד אחורי / ERP',
    'industries.back_office.description': 'ייעול תהליכים פיננסיים, ניהול מלאי והזנת נתונים עם אוטומציה חכמה.',
    'industries.back_office.challenge1': 'הזנת נתונים ידנית',
    'industries.back_office.challenge2': 'עיכובים בעיבוד חשבוניות',
    'industries.back_office.challenge3': 'אי התאמות במלאי',
    'industries.back_office.challenge4': 'יצירת דוחות',
    'industries.back_office.solution1': 'עיבוד חשבוניות אוטומטי',
    'industries.back_office.solution2': 'חילוץ נתונים חכם',
    'industries.back_office.solution3': 'מעקב מלאי בזמן אמת',
    'industries.back_office.solution4': 'דיווח אוטומטי',
    'industries.back_office.result1': '80% האצה בעיבוד',
    'industries.back_office.result2': '99% דיוק נתונים',
    'industries.back_office.result3': '65% הפחתת עלויות',
    
    'industries.horizontal.title': 'תהליכים אופקיים',
    'industries.horizontal.description': 'אוטומציה חוצת פונקציות עבור משאבי אנוש, פיננסים, שרשרת אספקה ותהליכים ארגוניים אחרים.',
    'industries.horizontal.challenge1': 'מערכות מבודדות',
    'industries.horizontal.challenge2': 'אישורים ידניים',
    'industries.horizontal.challenge3': 'אי עקביות נתונים',
    'industries.horizontal.challenge4': 'חוסר יעילות תהליכים',
    'industries.horizontal.solution1': 'תיאום זרימת עבודה',
    'industries.horizontal.solution2': 'אישורים אוטומטיים',
    'industries.horizontal.solution3': 'אינטגרציה של מערכות',
    'industries.horizontal.solution4': 'אופטימיזציה של תהליכים',
    'industries.horizontal.result1': '75% האצה באישורים',
    'industries.horizontal.result2': '90% יעילות תהליכים',
    'industries.horizontal.result3': 'נראות נתונים מאוחדת',
    
    'industries.medical.title': 'רפואה',
    'industries.medical.description': 'ייעול טיפול בחולים, ניהול רשומות רפואיות ותאימות תוך שמירה על תקני אבטחת HIPAA.',
    'industries.medical.challenge1': 'תיאום מורכב של מטופלים',
    'industries.medical.challenge2': 'עיבוד ידני של רשומות רפואיות',
    'industries.medical.challenge3': 'עיכובים בתביעות ביטוח',
    'industries.medical.challenge4': 'מעקב אחר תאימות רגולטורית',
    'industries.medical.solution1': 'תיאום מטופלים אוטומטי',
    'industries.medical.solution2': 'עיבוד חכם של רשומות רפואיות',
    'industries.medical.solution3': 'תביעות ביטוח אוטומטיות',
    'industries.medical.solution4': 'ניטור תאימות HIPAA',
    'industries.medical.result1': '60% האצה בעיבוד מטופלים',
    'industries.medical.result2': '90% דיוק תביעות',
    'industries.medical.result3': '40% הפחתה בעלויות אדמיניסטרטיביות',
    
    'industries.accounting.title': 'חשבונאות',
    'industries.accounting.description': 'אוטומציה של הנהלת חשבונות, הכנת מסים ודיווח פיננסי תוך הבטחת דיוק ותאימות.',
    'industries.accounting.challenge1': 'הזנת נתונים ידנית',
    'industries.accounting.challenge2': 'שגיאות בהתאמות',
    'industries.accounting.challenge3': 'הכנת מסים זוללת זמן',
    'industries.accounting.challenge4': 'עומס תקשורת עם לקוחות',
    'industries.accounting.solution1': 'הנהלת חשבונות אוטומטית',
    'industries.accounting.solution2': 'התאמות חכמות',
    'industries.accounting.solution3': 'הכנת מסים מונעת AI',
    'industries.accounting.solution4': 'אוטומציה של פורטל לקוחות',
    'industries.accounting.result1': '70% האצה בסגירת חודש',
    'industries.accounting.result2': '95% דיוק נתונים',
    'industries.accounting.result3': '50% יותר קיבולת לקוחות',
    
    'industries.legal.title': 'משפטים',
    'industries.legal.description': 'שיפור מחקר משפטי, בדיקת מסמכים וניהול תיקים עם אוטומציה וניתוח חכמים.',
    'industries.legal.challenge1': 'בדיקת מסמכים זוללת זמן',
    'industries.legal.challenge2': 'מחקר משפטי ידני',
    'industries.legal.challenge3': 'צווארי בקבוק בניתוח חוזים',
    'industries.legal.challenge4': 'מורכבות חיוב לקוחות',
    'industries.legal.solution1': 'בדיקת מסמכים מונעת AI',
    'industries.legal.solution2': 'מחקר משפטי אוטומטי',
    'industries.legal.solution3': 'ניתוח חוזים חכם',
    'industries.legal.solution4': 'מעקב זמן וחיוב אוטומטיים',
    'industries.legal.result1': '80% האצה בבדיקת מסמכים',
    'industries.legal.result2': '60% יעילות מחקר משופרת',
    'industries.legal.result3': '45% עלייה בשעות לחיוב',
    
    // Industries Common Labels
    'industries.common_challenges': 'אתגרים נפוצים',
    'industries.our_solutions': 'הפתרונות שלנו',
    'industries.typical_results': 'תוצאות טיפוסיות',
    'industries.ready_to_transform': 'מוכנים לשנות את התעשייה שלכם?',
    'industries.consultation_description': 'בואו נדבר על איך אוטומציית AI יכולה לפתור את האתגרים הספציפיים של התעשייה שלכם.',
    'industries.get_consultation': 'קבל ייעוץ ספציפי לתעשייה',
    'industries.title': 'תעשיות שאנו משנים',
    'industries.subtitle': 'פתרונות מיוחדים המותאמים לאתגרים ודרישות הייחודיים של התעשייה שלך',
    'industries.key_use_cases': 'מקרי שימוש עיקריים',
    
    // Process Section
    'process.title': 'התהליך שלנו',
    'process.subtitle': 'מתודולוגיה מוכחת שמבטיחה יישום AI מוצלח',
    'process.discover.title': 'גילוי',
    'process.discover.description': 'אנו מנתחים את התהליכים הנוכחיים שלך כדי לזהות הזדמנויות אוטומציה והישגים מהירים.',
    'process.discover.detail1': 'הערכת תהליכים',
    'process.discover.detail2': 'מיפוי הזדמנויות',
    'process.discover.detail3': 'ניתוח ROI',
    'process.pilot.title': 'פיילוט',
    'process.pilot.description': 'יצירת אבטיפוסים מהירים ובדיקה של פתרונות AI עם מדדי הצלחה מדידים.',
    'process.pilot.detail1': 'הוכחת מושג',
    'process.pilot.detail2': 'בדיקות ביצועים',
    'process.pilot.detail3': 'מדדי הצלחה',
    'process.scale.title': 'הרחבה',
    'process.scale.description': 'יישום מלא עם תשתית ברמה ארגונית וניהול שינוי.',
    'process.scale.detail1': 'פריסה מלאה',
    'process.scale.detail2': 'הכשרת צוות',
    'process.scale.detail3': 'ניהול שינוי',
    'process.operate.title': 'הפעלה',
    'process.operate.description': 'ייעול מתמשך, ניטור ותמיכה כדי להבטיח הצלחה מתמשכת.',
    'process.operate.detail1': 'ניטור ביצועים',
    'process.operate.detail2': 'ייעול מתמשך',
    'process.operate.detail3': 'תמיכה ותחזוקה',
    
     // Trust Section
    'trust.title': 'בטוחים באיכות ובתוצאות',
    'trust.subtitle': 'צטרפו לעשרות חברות מובילות שכבר חווים את התועלות של אוטומציה מבוססת AI',
    'trust.stats.clients': 'לקוחות ארגוניים',
    'trust.stats.automations': 'אוטומציות פעילות',
    'trust.stats.uptime': 'זמינות מובטחת',
    'trust.stats.costReduction': 'הפחתת עלויות ממוצעת',
    'trust.testimonials.testimonial1.quote': 'פתרונות האוטומציה מבוססת AI שינו את פעילות שירות הלקוחות שלנו, הפחיתו זמן תגובה ב-70% תוך שיפור ציוני שביעות הרצון.',
    'trust.testimonials.testimonial1.author': 'שרה ג׳ונסון',
    'trust.testimonials.testimonial1.role': 'סמנכ״ל תפעול',
    'trust.testimonials.testimonial1.company': 'TechCorp',
    'trust.testimonials.testimonial2.quote': 'ההטמעה הייתה חלקה וה-ROI היה ברור כבר ברבעון הראשון. הצוות שלנו יכול כעת להתמקד ביוזמות אסטרטגיות.',
    'trust.testimonials.testimonial2.author': 'מייקל צ׳ן',
    'trust.testimonials.testimonial2.role': 'מנכ״ל טכנולוגיות',
    'trust.testimonials.testimonial2.company': 'FinanceFlow',
    'trust.testimonials.testimonial3.quote': 'רמת ההתאמה האישית והאבטחה ברמה ארגונית עלתה על הציפיות שלנו. ממליץ בחום לכל פרויקט אוטומציה רציני.',
    'trust.testimonials.testimonial3.author': 'אמילי רודריגז',
    'trust.testimonials.testimonial3.role': 'מנהלת טכנולוגיות דיגיטליות',
    'trust.testimonials.testimonial3.company': 'ManufacturePlus',
    'trust.trustedBy': 'זוכים לאמון של חברות מובילות ברחבי העולם',
    
    // CTA Section
    'cta.title': 'מוכן לשנות את העסק שלך?',
    'cta.subtitle': 'התחל את מסע האוטומציה שלך היום עם ייעוץ חינם',
    'cta.button': 'התחל עכשיו',
    
    // Contact Page
    'contact.title': 'ספר לנו על הפרויקט שלך',
    'contact.subtitle': 'מלא את הטופס למטה ונחזור אליך תוך 24 שעות עם הצעה מותאמת אישית.',
    'contact.success': 'ההודעה נשלחה בהצלחה!',
    'contact.error': 'שליחת ההודעה נכשלה. אנא נסה שוב.',
    'contact.get_in_touch': 'צור קשר',
    'contact.phone': 'טלפון',
    'contact.email': 'אימייל',
    'contact.phone_description': 'דבר עם הצוות שלנו ישירות',
    'contact.email_description': 'שלח לנו הודעה מפורטת',
    'contact.phone_availability': 'ב׳-ו׳, 9:00-18:00 EST',
    'contact.email_availability': 'מענה תוך 24 שעות',
    'contact.quick_actions': 'פעולות מהירות',
    'contact.schedule_call': 'קבע שיחה',
    'contact.book_assessment': 'הזמן הערכה חינמית',
    'contact.promise': 'ההבטחה שלנו',
    'contact.promise_description': 'אנו מגיבים לכל הפניות תוך 24 שעות ומספקים הצעות מותאמות תוך 48 שעות.',
    'contact.form.name': 'שם מלא',
    'contact.form.email': 'כתובת אימייל',
    'contact.form.company': 'שם החברה',
    'contact.form.industry': 'תעשייה',
    'contact.form.industry.placeholder': 'בחר את התעשייה שלך',
    'contact.form.industry.healthcare': 'בריאות',
    'contact.form.industry.finance': 'פיננסים',
    'contact.form.industry.retail': 'קמעונאות',
    'contact.form.industry.manufacturing': 'ייצור',
    'contact.form.industry.technology': 'טכנולוגיה',
    'contact.form.industry.education': 'חינוך',
    'contact.form.industry.other': 'אחר',
    'contact.form.project_type': 'סוג פרויקט',
    'contact.form.project_type.placeholder': 'בחר סוג פרויקט',
    'contact.form.project_type.ai_automation': 'אוטומציה מבוססת AI',
    'contact.form.project_type.process_optimization': 'ייעול תהליכים',
    'contact.form.project_type.data_analysis': 'ניתוח נתונים',
    'contact.form.project_type.custom_integration': 'שילוב מותאם אישית',
    'contact.form.timeline': 'לוח זמנים',
    'contact.form.timeline.placeholder': 'בחר לוח זמנים',
    'contact.form.timeline.urgent': 'דחוף (מהיר)',
    'contact.form.timeline.1_3_months': '1-3 חודשים',
    'contact.form.timeline.3_6_months': '3-6 חודשים',
    'contact.form.timeline.6_plus_months': '6+ חודשים',
    'contact.form.budget': 'טווח תקציב',
    'contact.form.budget.placeholder': 'בחר טווח תקציב',
    'contact.form.budget.discuss': 'בוא נדבר',
    'contact.form.budget.10k_25k': '$10k - $25k',
    'contact.form.budget.25k_50k': '$25k - $50k',
    'contact.form.budget.50k_100k': '$50k - $100k',
    'contact.form.budget.100k_plus': '$100k+',
    'contact.form.message': 'פרטי הפרויקט',
    'contact.form.message.placeholder': 'ספר לנו על הפרויקט שלך, האתגרים הנוכחיים ומה אתה מקווה להשיג עם אוטומציה מבוססת AI...',
    'contact.form.submit': 'שלח הודעה',
    'contact.form.submitting': 'שולח...',

    // About Page
    'about.hero.title1': 'בונים את העתיד',
    'about.hero.title2': 'של אוטומציה עסקית',
    'about.hero.description': 'אנחנו במשימה לדמוקרטיזציה של אוטומציה מבוססת AI, להפוך פתרונות ברמה ארגונית נגישים לעסקים מכל הגדלים.',
    'about.mission.title': 'המשימה שלנו',
    'about.mission.description1': 'אנו מאמינים שאוטומציה מבוססת AI צריכה להיות בטוחה, ניתנת להרחבה ונגישה. המשימה שלנו היא לעזור לעסקים לרתום את כוח הבינה המלאכותית כדי לבטל עבודה חוזרת, להפחית שגיאות ולשחרר פוטנציאל אנושי.',
    'about.mission.description2': 'על ידי שילוב מומחיות טכנית עמוקה עם ניסיון עסקי מהעולם האמיתי, אנו מספקים פתרונות שלא רק עובדים—הם משנים איך עסקים פועלים ומתחרים.',
    'about.mission.learn_more': 'למד עוד על הגישה שלנו',
    'about.stats.clients': 'לקוחות ארגוניים',
    'about.stats.automations': 'אוטומציות פרוסות',
    'about.stats.experience': 'שנות ניסיון',
    'about.stats.uptime': 'זמינות',
    'about.values.title': 'הערכים שלנו',
    'about.values.description': 'העקרונות שמנחים כל מה שאנו עושים וכל פתרון שאנו בונים.',
    'about.values.trust.title': 'אמון',
    'about.values.trust.description': 'אנו בונים מערכות AI בטוחות ואמינות שעליהן ארגונים יכולים לסמוך עם אבטחה ותאימות ברמה ארגונית.',
    'about.values.innovation.title': 'חדשנות',
    'about.values.innovation.description': 'אנו נשארים בחזית טכנולוגיית AI כדי לספק פתרונות מתקדמים שמניעים ערך עסקי אמיתי.',
    'about.values.impact.title': 'השפעה',
    'about.values.impact.description': 'אנו מתמקדים בתוצאות מדידות שמשנות עסקים ויוצרות יתרונות תחרותיים מתמשכים.',
    'about.values.partnership.title': 'שותפות',
    'about.values.partnership.description': 'אנו עובדים בשיתוף הדוק עם הלקוחות שלנו כשותפים אמיתיים, מבטיחים אימוץ מוצלח והצלחה לטווח ארוך.',
    'about.team.title': 'הכירו את הצוות שלנו',
    'about.team.description': 'אנשי מקצוע מנוסים בעלי תשוקה לשנות עסקים באמצעות אוטומציה מבוססת AI.',
    'about.team.or.name': 'אור סלע',
    'about.team.or.role': 'מנכ״ל ומייסד',
    'about.team.or.speciality': 'אסטרטגיית AI ופיתוח עסקי',
    'about.team.or.description': 'מנהיג בעל חזון המוביל שינוי אוטומציה מבוססת AI ברחבי ארגונים.',
    'about.team.idan.name': 'עידן איילון',
    'about.team.idan.role': 'סמנכ״ל טכנולוגיות ומייסד',
    'about.team.idan.speciality': 'אדריכלות טכנית וחדשנות',
    'about.team.idan.description': 'מומחה בבניית מערכות AI ניתנות להרחבה ופלטפורמות אוטומציה.',
    'about.cta.title': 'מוכנים לעבוד יחד?',
    'about.cta.description': 'בואו נדון איך נוכל לעזור לשנות את העסק שלכם עם אוטומציה מבוססת AI.',
    'about.cta.button': 'התחילו את השיחה',
    
    // Marketplace
    'marketplace.title': 'חנות אוטומציה',
    'marketplace.subtitle': 'גלה ויישם תהליכי אוטומציה מוכנים',
    'marketplace.search.placeholder': 'חפש אוטומציות...',
    'marketplace.all_categories': 'כל הקטגוריות',
    'marketplace.automations_found': 'אוטומציות נמצאו',
    'marketplace.no_automations': 'לא נמצאו אוטומציות התואמות לקריטריונים שלך.',
    'marketplace.back_to_marketplace': 'חזור לחנות',
    'marketplace.use_automation': 'השתמש באוטומציה זו',
    'marketplace.watch_tutorial': 'צפה במדריך',
    'marketplace.about_automation': 'אודות האוטומציה',
    'marketplace.quality_score': 'ציון איכות',
    'marketplace.category': 'קטגוריה',
    'marketplace.platform': 'פלטפורמה',
    
    // Not Found
    'notfound.title': '404',
    'notfound.subtitle': 'אופס! הדף לא נמצא',
    'notfound.back_home': 'חזור לדף הבית',

    // Resources Page
    'resources.title': 'מרכז ידע',
    'resources.subtitle': 'חקור את הספרייה המקיפה שלנו של מדריכים, מקרי בוחן ותובנות כדי להאיץ את מסע האוטומציה המבוסס AI שלך.',
    'resources.guides.title': 'מדריכים ומסמכי עמדה',
    'resources.guides.whitepaper.type': 'מסמך עמדה',
    'resources.guides.whitepaper.duration': '15 דקות קריאה',
    'resources.guides.whitepaper.title': 'מדריך יישום AI ארגוני',
    'resources.guides.whitepaper.description': 'מדריך מקיף ליישום פתרונות AI בסביבות ארגוניות.',
    'resources.guides.guide.type': 'מדריך',
    'resources.guides.guide.duration': '10 דקות קריאה',
    'resources.guides.guide.title': 'שיטות עבודה מומלצות ל-RPA לצוותי כספים',
    'resources.guides.guide.description': 'למד כיצד ליישם בהצלחה RPA בתהליכים פיננסיים.',
    'resources.guides.framework.type': 'מסגרת עבודה',
    'resources.guides.framework.duration': '20 דקות קריאה',
    'resources.guides.framework.title': 'מסגרת בטיחות וממשל AI',
    'resources.guides.framework.description': 'מסגרת חיונית להבטחת בטיחות AI ותאימות בארגון שלך.',
    'resources.cases.title': 'מקרי בוחן',
    'resources.cases.fintech.type': 'מקרה בוחן',
    'resources.cases.fintech.duration': '8 דקות קריאה',
    'resources.cases.fintech.title': 'חברת פינטק מפחיתה זמני עיבוד ב-80%',
    'resources.cases.fintech.description': 'כיצד פינטק מוביל הפך את תהליך איוש הלקוחות לאוטומטי.',
    'resources.cases.manufacturing.type': 'מקרה בוחן',
    'resources.cases.manufacturing.duration': '12 דקות קריאה',
    'resources.cases.manufacturing.title': 'ענק ייצור מייעל את שרשרת האספקה',
    'resources.cases.manufacturing.description': 'ייעול שרשרת אספקה מבוסס AI מביא ל-60% שיפור ביעילות.',
    'resources.webinars.title': 'וובינרים וסרטונים',
    'resources.webinars.future.type': 'וובינר',
    'resources.webinars.future.duration': '45 דקות צפייה',
    'resources.webinars.future.title': 'עתיד האוטומציה של AI ב-2024',
    'resources.webinars.future.description': 'הצטרף למומחים שלנו כשהם דנים במגמות חדשות באוטומציה של AI.',
    'resources.webinars.generative.type': 'סדרת סרטונים',
    'resources.webinars.generative.duration': '30 דקות צפייה',
    'resources.webinars.generative.title': 'התחלת עבודה עם AI גנרטיבי',
    'resources.webinars.generative.description': 'מבוא מעשי ליישום AI גנרטיבי בעסק שלך.',
    'resources.insights.title': 'תובנות אחרונות',
    'resources.insights.subtitle': 'הישאר מעודכן עם המגמות והתובנות האחרונות באוטומציה של AI.',
    'resources.insights.trends.category': 'מגמות',
    'resources.insights.trends.date': '15 במרץ, 2024',
    'resources.insights.trends.title': 'מגמות היפר-אוטומציה: מה לצפות ב-2024',
    'resources.insights.trends.description': 'חקור את המגמות החדשות בהיפר-אוטומציה וכיצד הן יעצבו תהליכים עסקיים.',
    'resources.insights.trends.duration': '5 דקות קריאה',
    'resources.insights.ethics.category': 'אתיקה של AI',
    'resources.insights.ethics.date': '10 במרץ, 2024',
    'resources.insights.ethics.title': 'בניית מערכות AI אתיות לארגון',
    'resources.insights.ethics.description': 'שיטות עבודה מומלצות לפיתוח מערכות AI אתיות, שקופות ותואמות.',
    'resources.insights.ethics.duration': '8 דקות קריאה',
    'resources.insights.business.category': 'ערך עסקי',
    'resources.insights.business.date': '5 במרץ, 2024',
    'resources.insights.business.title': 'מחשבון ROI: מדידת הצלחה באוטומציה של AI',
    'resources.insights.business.description': 'למד כיצד לחשב ולעקוב אחר ROI של יוזמות האוטומציה של AI שלך.',
    'resources.insights.business.duration': '6 דקות קריאה',
    'resources.newsletter.title': 'הישאר מעודכן',
    'resources.newsletter.description': 'קבל את התובנות והמשאבים האחרונים במייל שלך מדי חודש.',
    'resources.newsletter.button': 'הירשם לניוזלטר',
    'resources.download': 'הורד',
    'resources.read_more': 'קרא עוד',
    'resources.view_all_posts': 'צפה בכל הפוסטים',

    // Solutions Page
    'solutions.hero.title': 'פתרונות שנבנו',
    'solutions.hero.subtitle': 'להשפעה אמיתית',
    'solutions.hero.description': 'פתרונות AI ואוטומציה מקיפים שנועדו לשנות את פעולות העסק שלך ולהניע תוצאות מדידות.',
    'solutions.ai_automation.title': 'אוטומציה מבוססת AI',
    'solutions.ai_automation.description': 'תהליכי עבודה חכמים שמתאימים ומתייעלים בעצמם, מפחיתים התערבות ידנית תוך הגדלת דיוק ומהירות.',
    'solutions.ai_automation.feature1': 'כריית תהליכים חכמה',
    'solutions.ai_automation.feature2': 'תהליכי עבודה מתאימים',
    'solutions.ai_automation.feature3': 'אנליטיקה חזויה',
    'solutions.ai_automation.feature4': 'ייעול בזמן אמת',
    'solutions.ai_automation.benefit1': '60% הפחתה בזמני עיבוד',
    'solutions.ai_automation.benefit2': '95% שיפור בדיוק',
    'solutions.ai_automation.benefit3': 'פעולות אוטומטיות 24/7',
    'solutions.generative_ai.title': 'פתרונות AI גנרטיביים',
    'solutions.generative_ai.description': 'מודלי AI מותאמים אישית ליצירת תוכן, ניתוח נתונים ותמיכה בהחלטות המותאמים לצרכי העסק שלך.',
    'solutions.generative_ai.feature1': 'שילוב LLM מותאם אישית',
    'solutions.generative_ai.feature2': 'יצירת תוכן',
    'solutions.generative_ai.feature3': 'תובנות נתונים',
    'solutions.generative_ai.feature4': 'עיבוד שפה טבעית',
    'solutions.generative_ai.benefit1': '3x יצירת תוכן מהירה יותר',
    'solutions.generative_ai.benefit2': 'אינטראקציות לקוחות מותאמות אישית',
    'solutions.generative_ai.benefit3': 'יצירת דוחות אוטומטית',
    'solutions.enterprise_ai.title': 'פיתוח AI ארגוני',
    'solutions.enterprise_ai.description': 'פיתוח מערכות AI מקצה לקצה עם אבטחה ברמה ארגונית, מדרגיות וממשל.',
    'solutions.enterprise_ai.feature1': 'ארכיטקטורה מדרגית',
    'solutions.enterprise_ai.feature2': 'אבטחה קודם כל',
    'solutions.enterprise_ai.feature3': 'מוכן לתאימות',
    'solutions.enterprise_ai.feature4': 'יכולות שילוב',
    'solutions.enterprise_ai.benefit1': 'אבטחה ברמה ארגונית',
    'solutions.enterprise_ai.benefit2': 'שילוב מערכות חלק',
    'solutions.enterprise_ai.benefit3': 'תאימות רגולטורית',
    'solutions.consulting.title': 'ייעוץ ואימוץ AI',
    'solutions.consulting.description': 'הנחיה אסטרטגית לזיהוי הזדמנויות, תכנון יישום והבטחת אימוץ AI מוצלח.',
    'solutions.consulting.feature1': 'פיתוח אסטרטגיה',
    'solutions.consulting.feature2': 'ניהול שינוי',
    'solutions.consulting.feature3': 'תוכניות הכשרה',
    'solutions.consulting.feature4': 'ניטור ביצועים',
    'solutions.consulting.benefit1': 'מפת דרכים AI ברורה',
    'solutions.consulting.benefit2': 'אימוץ צוות מוצלח',
    'solutions.consulting.benefit3': 'ROI מדיד',
    'solutions.rpa.title': 'אוטומציה רובוטית של תהליכים',
    'solutions.rpa.description': 'RPA מסורתי משופר עם יכולות AI לאוטומציה מורכבת של תהליכים וטיפול בחריגות.',
    'solutions.rpa.feature1': 'RPA חכם',
    'solutions.rpa.feature2': 'טיפול בחריגות',
    'solutions.rpa.feature3': 'ייעול תהליכים',
    'solutions.rpa.feature4': 'שילוב מערכות מורשת',
    'solutions.rpa.benefit1': '80% עיבוד מהיר יותר',
    'solutions.rpa.benefit2': 'הפחתת שגיאות אנושיות',
    'solutions.rpa.benefit3': 'מודרניזציה של מערכות מורשת',
    'solutions.key_features': 'תכונות מרכזיות:',
    'solutions.benefits': 'יתרונות:',
    'solutions.visual.placeholder': 'הדמיית פתרון',
    'solutions.cta.title': 'מוכן',
    'solutions.cta.subtitle': 'להתחיל?',
    'solutions.cta.description': 'בואו נדון איזה פתרון מתאים לצרכי העסק שלך.',
    'solutions.cta.button': 'קבע פגישת אסטרטגיה',

    // Assistant Chat
    'assistant.greeting': 'איך אני יכול לעזור לעסק שלך?',
    'assistant.input_placeholder': 'שאל אותי על אוטומציית AI...',
    'assistant.hello_response': 'שלום! אני כאן כדי לעזור לך לגלות איך אוטומציית AI יכולה לשנות את העסק שלך. באילו אתגרים אתה מתמודד?',
    'assistant.automation_response': 'אוטומציית AI יכולה לעזור לייעל את הפעילות שלך, להפחית עלויות ולשפר יעילות. האם תרצה לדעת יותר על הפתרונות שלנו לתעשייה הספציפית שלך?',
    'assistant.cost_response': 'הפתרונות שלנו מותאמים לצרכים ותקציב הספציפיים שלך. אנו מציעים אפשרויות תמחור גמישות החל מ-$10k. האם תרצה לקבוע ייעוץ חינמי כדי לדון בדרישות שלך?',
    'assistant.contact_response': 'אני אשמח לעזור לך ליצור קשר עם הצוות שלנו! תוכל לקבוע שיחת אסטרטגיה או ליצור קשר ישירות. מה תעדיף?',
    'assistant.default_response': 'זאת שאלה מעולה! פתרונות האוטומציה שלנו יכולים לעזור עם אתגרים עסקיים שונים. האם תוכל לספר לי יותר על הצרכים הספציפיים שלך כדי שאוכל לספק סיוע ממוקד יותר?',

    // Onboarding
    'onboarding.title': 'היי, אני מייט!',
    'onboarding.message': 'אני העוזר שלך, בוא נדבר על העסק שלך ואיך אוטומציית AI יכולה לעזור לך לצמוח.',
    'onboarding.start_chat': 'בוא נדבר!',
    'onboarding.maybe_later': 'אולי מאוחר יותר',

    // App Builder Page  
    'app_builder.hero.title_a': 'מרעיון לאפליקציה עובדת תוך 30 דקות',
    'app_builder.hero.subtitle_a': 'ראה את האפליקציה שלך מתעוררת לחיים לפני שתשקיע אפילו אגורה',
    'app_builder.hero.title_b': 'ראה את האפליקציה שלך לפני שתבנה אותה',
    'app_builder.hero.subtitle_b': 'קבל אבטיפוס עובד לבדיקה עם משתמשים ומשקיעים',
    'app_builder.hero.title_c': 'דע בדיוק כמה האפליקציה שלך תעלה ואיך היא תיראה',
    'app_builder.hero.subtitle_c': 'קבל תמחור מדויק, לוח זמנים ואבטיפוס עובד לבדיקה',
    'app_builder.hero.title_d': 'לא נדרש ידע טכני',
    'app_builder.hero.subtitle_d': 'הבינה המלאכותית שלנו מטפלת בדברים המורכבים, אתה מתמקד בחזון שלך',
    
    'app_builder.process.docs_title': 'קבל מסמכים מקצועיים',
    'app_builder.process.docs_description': 'מסמך דרישות מוצר, ארכיטקטורה ותרשימי זרימה',
    'app_builder.process.prototype_title': 'ראה אבטיפוס עובד',
    'app_builder.process.prototype_description': 'בדוק את האפליקציה שלך בזמן אמת',
    'app_builder.process.quote_title': 'קבל הצעת מחיר מדויקת ואבטיפוס',
    'app_builder.process.quote_description': 'דע בדיוק כמה זה יעלה ותראה איך זה נראה',
    
    'app_builder.form.title': 'קבל את חבילת האפליקציה המלאה שלך תוך 24 שעות',
    'app_builder.form.subtitle': 'מסמכים מקצועיים + אבטיפוס עובד + תמחור מדויק - כל מה שאתה צריך להתקדם',
    'app_builder.form.name_label': 'שם מלא',
    'app_builder.form.email_label': 'כתובת אימייל',
    'app_builder.form.idea_label': 'תאר את רעיון האפליקציה שלך',
    'app_builder.form.idea_placeholder': 'ספר לנו מה האפליקציה צריכה לעשות, למי היא מיועדת ואילו בעיות היא פותרת...',
    'app_builder.form.industry_label': 'תעשייה',
    'app_builder.form.industry_placeholder': 'לדוגמה: בריאות, פיננסים, מסחר אלקטרוני',
    'app_builder.form.timeline_label': 'לוח זמנים רצוי',
    'app_builder.form.timeline_placeholder': 'לדוגמה: 3 חודשים, בהקדם האפשרי, רבעון שני 2025',
    'app_builder.form.submit': 'קבל את החבילה המלאה שלי',
    'app_builder.form.disclaimer': 'ללא התחייבות • ראה עלות ואבטיפוס קודם • משלוח תוך 24 שעות',
    
    'app_builder.features.speed_title': 'מהיר כברק',
    'app_builder.features.speed_description': 'קבל את האבטיפוס העובד שלך תוך 24 שעות, לא שבועות. מושלם לפגישות עם משקיעים ובדיקות משתמשים.',
    'app_builder.features.risk_title': 'אימות ללא סיכון',
    'app_builder.features.risk_description': 'ראה בדיוק מה אתה מקבל לפני שתשקיע בפיתוח מלא. אין הפתעות, אין חרטות.',
    'app_builder.features.time_title': 'חסוך חודשים',
    'app_builder.features.time_description': 'דלג על שלב הגילוי המסורתי. השיחה עם הבינה המלאכותית שלנו מחלצת כל מה שנדרש לתכנון מדויק.',
    
    'app_builder.trust.title': 'למה מייסדים חכמים בוחרים במערכת האימות שלנו',
    'app_builder.social_proof.quote': 'האבטיפוס הזה עזר לנו לגייס 2 מיליון דולר במימון ראשוני. המשקיעים באמת יכלו לראות ולבדוק את החזון שלנו.',
    'app_builder.social_proof.author': 'שרה צ\'ן, מנכ"לית TechStart (Y Combinator W23)',
    
    'app_builder.chat.demo_title': 'נסה את בונה האפליקציות האוטומטי שלנו',
    'app_builder.chat.demo_subtitle': 'חווה איך השיחה החכמה שלנו הופכת רעיון אפליקציה לאבטיפוס עובד',
    'app_builder.chat.start_button': 'התחל לבנות את האפליקציה שלי',
    'app_builder.chat.disclaimer': 'ללא הרשמה נדרשת • ראה תוצאות מיד • לוקח 2 דקות',

    // Common
    'common.automate': '\mates',
    'common.loading': 'טוען...',
    'common.learn_more': 'למד עוד',
    'common.get_started': 'התחל כעת',
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('he');

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations[typeof language]] || key;
  };

  const isRTL = language === 'he';

  useEffect(() => {
    document.documentElement.dir = isRTL ? 'rtl' : 'ltr';
    document.documentElement.lang = language;
    // Update document title based on language
    document.title = t('common.automate');
  }, [isRTL, language, t]);

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, isRTL }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};